name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake (Light)
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake.svg
          snake_color: '#4CAF50'

      - name: Generate Snake (Dark)
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-snake-dark.svg
          snake_color: '#4CAF50'
          color_snake: '#4CAF50'
          color_dots: '#2F80ED,#4CAF50,#2196F3,#FF9800,#F44336'

      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
